### ISSUE TITLE
突然发现作者的docker是可执行文件

### ISSUE THREAD

**Issue by DayDreammy** [devcxl/WeChatBot#21]
我本来是想直接在docker里面修改代码的，这样就不用配环境了哈哈。

**Comment by devcxl** [comment]
是的，为了精简docker用pyinstaller打包了。改代码的话你可以fork代码之后参考`.github/workflows/build.yaml` 用Github Action自动构建自己的镜像

**Comment by DayDreammy** [comment]
ok，感谢。我试试
